from . import help
from . import start
from . import tugmalar
from . import roza_duosi
from . import namoz_oqish
from . import quron_tinglash
from . import Qism
from . import uchinchi_qism
from . import tortinchi_qism
from . import beshinchi_qism
from . import oltinchi_qism
from . import maruzalar
from . import Quron_kitob
from . import Namoz_kitob
from . import saodat_asri
from . import olti_diniy_kalima
from . import birinchi_din
from . import ikkinchi_din
from . import uchinchi_din
from . import tortinchi_din
from . import beshinchi_din
from . import oltinchi_din
from . import Allohning_ismlari
from . import echo
